export const SESSION_LIST_LIMIT = 30
export const SESSION_LIST_PAGE_SIZE = 30
export const MESSAGE_PAGE_SIZE = 100
export const MESSAGE_TOP_UNLOAD_THRESHOLD = 200
export const MESSAGE_TOP_SENTINEL_THRESHOLD = 80
export const MESSAGE_TOP_MEASURE_FALLBACK = 96
