import { afterEach, beforeEach, describe, expect, it } from "bun:test"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import {
  applyManifestToVscodePackage,
  extractLatestVersionMarkdown,
  renderJetBrainsChangelogHtml,
  renderJetBrainsDescriptionHtml,
  renderReadme,
  renderVscodeChangelog,
  syncReleaseContent,
} from "./release-content"

const manifest = {
  title: "OpenCode UI (unofficial)",
  shortDescription:
    "OpenCode UI (unofficial) brings local OpenCode AI workflows into IDEs with chat, context management, and bundled backend binaries.",
  vscodeReadmeNote:
    "This package is published as a VSCode extension and integrates OpenCode into the activity bar, Explorer context menu, and editor context menu.",
  jetbrainsReadmeNote:
    "This package is published as a JetBrains plugin and integrates OpenCode into the tool window, Project View, and editor popup actions.",
}

const readmeBody = `# OpenCode UI (unofficial)

OpenCode UI (unofficial) brings local OpenCode AI workflows into IDEs with chat, context management, and bundled backend binaries.

## Core capabilities

- Drag and drop files into context
- Add all opened files to context via command or shortcut
- Add the current file to context via command or shortcut
- Add selected line ranges to context via command or shortcut
- Use a dedicated input area for easier prompt drafting and editing

## Important note

This is an unofficial plugin. Install only one OpenCode IDE variant to avoid duplicate features or conflicting behavior.

## Standard release

The current release track is the standard variant. It bundles the OpenCode backend for supported platforms and launches it locally at runtime.

## Who this is for

This plugin is designed for developers already using OpenCode who want to stay inside the IDE for chat, context management, and local AI coding workflows.
`

const descriptionBody = `OpenCode UI (unofficial) brings local OpenCode AI workflows into IDEs with chat, context management, and bundled backend binaries.

## Overview

OpenCode UI (unofficial) is an unofficial IDE plugin that brings local OpenCode workflows into the editor. You can open a chat sidebar, refine prompts in place, and move project context into the conversation without bouncing between the IDE and a terminal.

## Core capabilities

- Drag and drop files into context
- Add all opened files to context via command or shortcut
- Add the current file to context via command or shortcut
- Add selected line ranges to context via command or shortcut
- Use a dedicated input area for easier prompt drafting and editing

## Important note

This is an unofficial plugin. Install only one OpenCode IDE variant to avoid duplicate features or conflicting behavior.

## Standard release

The current release track is the standard variant. It bundles the OpenCode backend for supported platforms and launches it locally at runtime.

## Who this is for

This plugin is designed for developers already using OpenCode who want to stay inside the IDE for chat, context management, and local AI coding workflows.
`

const changelogBody = `# Changelog

## v26.5.303

### 近期重点改进
- 补齐 JetBrains 宿主侧能力，持续向 VSCode 端体验对齐。
- 支持 host-aware 重启动作，在不同宿主环境下提供更准确的重启入口。
- 继续完善中文本地化，补齐模型、工具权限、错误提示等关键文案。

### 功能演进概览
- 支持文件拖拽加入上下文、当前文件加入上下文、已打开文件批量加入上下文，以及选中代码行范围加入上下文。
- 完成浏览器式标签体系建设，支持拖拽、重命名、右键菜单、自动滚动与数量限制。
- 引入快捷短语、子任务抽屉、任务进度头与更易编辑的输入区域，提升日常使用效率。
- 统一宿主侧状态持久化策略，改进主题、设置、会话与草稿状态恢复体验。

### 修复与体验优化
- 优化常用短语预设，提升 IDE 内提示词输入效率。
- 增强 WebView 滚动体验并支持 \`jcefScrollMultiplier\` 参数调节滚动灵敏度。
- 改进流式输出、会话恢复、标签状态持久化与长会话稳定性。
- 移除旧的仅界面变体说明，统一标准版单路线发布文案与打包认知。

## v26.4.2903

### 近期重点改进
- 旧版本样本，用于验证 JetBrains changelog 只取最新版本。
`

describe("release content renderers", () => {
  it("renders readme with a generated banner and platform note", () => {
    const output = renderReadme(readmeBody, manifest.vscodeReadmeNote)

    expect(output.startsWith("<!-- Generated by bun run release-content:sync. Do not edit directly. -->")).toBeTrue()
    expect(output).toContain("## Platform note")
    expect(output).toContain(manifest.vscodeReadmeNote)
    expect(output).not.toContain("GUI only")
  })

  it("renders a JetBrains description that starts with the plain short description", () => {
    const output = renderJetBrainsDescriptionHtml(descriptionBody)

    expect(output.startsWith(manifest.shortDescription)).toBeTrue()
    expect(output).toContain("<h2>Overview</h2>")
    expect(output).toContain("<li>Drag and drop files into context</li>")
  })

  it("extracts the latest changelog section and converts it to JetBrains HTML", () => {
    expect(extractLatestVersionMarkdown(changelogBody)).toContain("## v26.5.303")

    const output = renderJetBrainsChangelogHtml(changelogBody)
    expect(output).toContain("<h2>更新内容</h2>")
    expect(output).toContain("<h3>v26.5.303</h3>")
    expect(output).not.toContain("v26.4.2903")
  })

  it("updates only the shared VSCode package metadata fields", () => {
    const output = applyManifestToVscodePackage(
      JSON.stringify({
        name: "opencode-ui",
        publisher: "caiqy",
        version: "26.5.100",
        displayName: "Old",
        description: "Old",
      }),
      manifest,
    )

    const pkg = JSON.parse(output)
    expect(pkg.name).toBe("opencode-ui")
    expect(pkg.publisher).toBe("caiqy")
    expect(pkg.displayName).toBe(manifest.title)
    expect(pkg.description).toBe(manifest.shortDescription)
  })

  it("renders the shared changelog for VSCode as markdown with a generated banner", () => {
    const output = renderVscodeChangelog(changelogBody)

    expect(output.startsWith("<!-- Generated by bun run release-content:sync. Do not edit directly. -->")).toBeTrue()
    expect(output).toContain("## v26.5.303")
    expect(output).toContain("### 修复与体验优化")
  })
})

let tempRoot = ""

beforeEach(async () => {
  tempRoot = await mkdtemp(path.join(os.tmpdir(), "release-content-"))

  await mkdir(path.join(tempRoot, "docs/release-content"), { recursive: true })
  await mkdir(path.join(tempRoot, "hosts/vscode-plugin"), { recursive: true })
  await mkdir(path.join(tempRoot, "hosts/jetbrains-plugin"), { recursive: true })

  await writeFile(path.join(tempRoot, "docs/release-content/manifest.json"), JSON.stringify(manifest, null, 2) + "\n")
  await writeFile(path.join(tempRoot, "docs/release-content/README.shared.md"), readmeBody + "\n")
  await writeFile(path.join(tempRoot, "docs/release-content/description.shared.md"), descriptionBody + "\n")
  await writeFile(path.join(tempRoot, "docs/release-content/CHANGELOG.md"), changelogBody + "\n")
  await writeFile(
    path.join(tempRoot, "hosts/vscode-plugin/package.json"),
    JSON.stringify(
      {
        name: "opencode-ui",
        publisher: "caiqy",
        version: "26.5.100",
        displayName: "stale",
        description: "stale",
      },
      null,
      2,
    ) + "\n",
  )
  await writeFile(path.join(tempRoot, "hosts/vscode-plugin/README.md"), "stale\n")
  await writeFile(path.join(tempRoot, "hosts/vscode-plugin/CHANGELOG.md"), "stale\n")
  await writeFile(path.join(tempRoot, "hosts/jetbrains-plugin/README.md"), "stale\n")
  await writeFile(path.join(tempRoot, "hosts/jetbrains-plugin/description.html"), "stale\n")
  await writeFile(path.join(tempRoot, "hosts/jetbrains-plugin/changelog.html"), "stale\n")
})

afterEach(async () => {
  if (tempRoot) await rm(tempRoot, { recursive: true, force: true })
})

describe("syncReleaseContent", () => {
  it("writes generated files for both platforms", async () => {
    await syncReleaseContent(tempRoot)

    const vscodeReadme = await readFile(path.join(tempRoot, "hosts/vscode-plugin/README.md"), "utf8")
    const vscodePackage = JSON.parse(await readFile(path.join(tempRoot, "hosts/vscode-plugin/package.json"), "utf8"))
    const jetbrainsDescription = await readFile(path.join(tempRoot, "hosts/jetbrains-plugin/description.html"), "utf8")
    const jetbrainsChangelog = await readFile(path.join(tempRoot, "hosts/jetbrains-plugin/changelog.html"), "utf8")

    expect(vscodeReadme).toContain("## Platform note")
    expect(vscodeReadme).not.toContain("GUI only")
    expect(vscodePackage.displayName).toBe(manifest.title)
    expect(vscodePackage.description).toBe(manifest.shortDescription)
    expect(jetbrainsDescription.startsWith(manifest.shortDescription)).toBeTrue()
    expect(jetbrainsChangelog).toContain("<h2>更新内容</h2>")
    expect(jetbrainsChangelog).not.toContain("v26.4.2903")
  })

  it("fails check mode when generated outputs are stale", async () => {
    await expect(syncReleaseContent(tempRoot, { check: true })).rejects.toThrow(
      "Generated release content is out of date",
    )
  })
})
