import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

export type ReleaseContentManifest = {
  title: string
  shortDescription: string
  vscodeReadmeNote: string
  jetbrainsReadmeNote: string
}

export type SyncOptions = {
  check?: boolean
}

export const generatedBanner = "<!-- Generated by bun run release-content:sync. Do not edit directly. -->"

const normalize = (text: string) => text.trim().replace(/\r\n/g, "\n")

const escapeHtml = (text: string) => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")

const renderInline = (text: string) =>
  escapeHtml(text).replace(/`([^`]+)`/g, (_match, code) => `<code>${escapeHtml(code)}</code>`)

const markdownToHtml = (markdown: string) => {
  const html: string[] = []
  const lines = normalize(markdown).split("\n")
  const paragraph: string[] = []
  const list: string[] = []

  const flushParagraph = () => {
    if (paragraph.length === 0) return
    html.push(`<p>${renderInline(paragraph.join(" "))}</p>`)
    paragraph.length = 0
  }

  const flushList = () => {
    if (list.length === 0) return
    html.push(`<ul>\n${list.map((item) => `  <li>${renderInline(item)}</li>`).join("\n")}\n</ul>`)
    list.length = 0
  }

  for (const raw of lines) {
    const line = raw.trim()

    if (!line) {
      flushParagraph()
      flushList()
      continue
    }

    if (line.startsWith("- ")) {
      flushParagraph()
      list.push(line.slice(2))
      continue
    }

    flushList()

    if (line.startsWith("### ")) {
      flushParagraph()
      html.push(`<h3>${renderInline(line.slice(4))}</h3>`)
      continue
    }

    if (line.startsWith("## ")) {
      flushParagraph()
      html.push(`<h2>${renderInline(line.slice(3))}</h2>`)
      continue
    }

    if (line.startsWith("# ")) {
      flushParagraph()
      html.push(`<h1>${renderInline(line.slice(2))}</h1>`)
      continue
    }

    paragraph.push(line)
  }

  flushParagraph()
  flushList()

  return `${html.join("\n\n")}\n`
}

export const renderReadme = (body: string, platformNote: string) =>
  `${generatedBanner}\n\n${normalize(body)}\n\n## Platform note\n\n${platformNote.trim()}\n`

export const renderVscodeChangelog = (markdown: string) => `${generatedBanner}\n\n${normalize(markdown)}\n`

export const extractLatestVersionMarkdown = (markdown: string) => {
  const normalized = normalize(markdown)
  const matches = [...normalized.matchAll(/^##\s+v[^\n]+$/gm)]
  if (matches.length === 0) throw new Error("Shared changelog is missing a version heading")
  const start = matches[0]?.index ?? 0
  const end = matches[1]?.index ?? normalized.length
  return normalized.slice(start, end).trim()
}

export const renderJetBrainsDescriptionHtml = (markdown: string) => {
  const lines = normalize(markdown).split("\n")
  const lead = lines.shift()?.trim() ?? ""
  const rest = lines.join("\n").trim()
  return rest ? `${lead}\n\n${markdownToHtml(rest)}` : `${lead}\n`
}

export const renderJetBrainsChangelogHtml = (markdown: string) => {
  const latest = extractLatestVersionMarkdown(markdown).replace(/^##\s+/m, "### ")
  return `<h2>更新内容</h2>\n\n${markdownToHtml(latest)}`
}

export const applyManifestToVscodePackage = (packageText: string, manifest: ReleaseContentManifest) => {
  const pkg = JSON.parse(packageText)
  pkg.displayName = manifest.title
  pkg.description = manifest.shortDescription
  return `${JSON.stringify(pkg, null, 2)}\n`
}

const loadSharedReleaseContent = async (root: string) => {
  const read = (filePath: string) => readFile(path.join(root, filePath), "utf8")
  const manifest = JSON.parse(await read("docs/release-content/manifest.json")) as ReleaseContentManifest

  return {
    manifest,
    readme: await read("docs/release-content/README.shared.md"),
    description: await read("docs/release-content/description.shared.md"),
    changelog: await read("docs/release-content/CHANGELOG.md"),
    vscodePackage: await read("hosts/vscode-plugin/package.json"),
  }
}

export const buildReleaseContentFiles = async (root: string) => {
  const { manifest, readme, description, changelog, vscodePackage } = await loadSharedReleaseContent(root)

  return new Map<string, string>([
    [path.join(root, "hosts/vscode-plugin/README.md"), renderReadme(readme, manifest.vscodeReadmeNote)],
    [path.join(root, "hosts/vscode-plugin/CHANGELOG.md"), renderVscodeChangelog(changelog)],
    [path.join(root, "hosts/vscode-plugin/package.json"), applyManifestToVscodePackage(vscodePackage, manifest)],
    [path.join(root, "hosts/jetbrains-plugin/README.md"), renderReadme(readme, manifest.jetbrainsReadmeNote)],
    [path.join(root, "hosts/jetbrains-plugin/description.html"), renderJetBrainsDescriptionHtml(description)],
    [path.join(root, "hosts/jetbrains-plugin/changelog.html"), renderJetBrainsChangelogHtml(changelog)],
  ])
}

export const syncReleaseContent = async (root: string, options: SyncOptions = {}) => {
  const files = await buildReleaseContentFiles(root)
  const stale: string[] = []

  for (const [filePath, expected] of files) {
    let current = ""
    try {
      current = await readFile(filePath, "utf8")
    } catch {
      current = ""
    }

    if (current === expected) continue

    if (options.check) {
      stale.push(path.relative(root, filePath))
      continue
    }

    await mkdir(path.dirname(filePath), { recursive: true })
    await writeFile(filePath, expected)
  }

  if (stale.length > 0) {
    throw new Error(`Generated release content is out of date:\n${stale.join("\n")}`)
  }

  if (options.check) {
    console.log("release content is in sync")
    return
  }

  console.log(`updated ${files.size} release content files`)
}
